# Generated by Django 3.0.8 on 2020-07-04 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='destinations',
            unique_together=set(),
        ),
    ]
